ne10: fix build with gcc 4.9
CXXFLAGS_append += " -std=c++11" breaks the build.

/home/hains/openpli-oe-core/build/tmp/work/cortexa9-vfp-oe-linux-gnueabi/ne10/1.2.1gitr+AUTOINC+18c4c982a5-r0/git/samples/
NE10_sample_fir.c:86:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
|      for (int b = 0; b < NUMBLOCKS; b++)
|      ^